extends: airbnb-base
rules:
  no-console: off
  func-names: off
  consistent-return: off
  object-curly-newline: ["error", "consistent": true]
  no-unused-vars: ["error", "args": "none"]
  no-underscore-dangle:
  - error
  - allow:
    - _id